packages:
  - 'apps/*'
  - 'packages/*'
  - '!**/test/**'
  - '!**/dist/**'

catalog:
  '@vueuse/core': ^12.3.0
  '@vueuse/components': ^12.3.0
  '@vueuse/nuxt': ^12.3.0
  '@vitejs/plugin-vue': ^5.2.1
  '@rushstack/eslint-patch': ^1.7.2
  '@tsconfig/node18': ^18.2.2
  '@types/node': ^20.11.24
  '@nuxtjs/eslint-config-typescript': ^12.1.0
  '@nuxt/ui': ^2.20.0
  '@unocss/nuxt': ^0.65.3
  pinia: ^2.2.2
  vue: ^3.5.13
  vue-router: ^4.5.0
  typescript: ^5.6.3
  unocss: ^0.65.3
  vite: ^6.0.5
  vue-tsc: ^2.1.10
  eslint: ^8.57.0
  eslint-plugin-vue: ^9.22.0
  npm-run-all2: ^6.1.2
  prettier: ^3.2.5
  turbo: ^2.3.3
  nuxt: ^3.15.0
  nuxt-icon: ^0.6.9
